const products = [
  { name: 'Футболка', category: 'Верхній одяг', price: 25.99 },
  { name: 'Джинси', category: 'Низ', price: 49.99 },
  { name: 'Світшот', category: 'Верхній одяг', price: 35.99 },
  { name: 'Шапка', category: 'Головний убір', price: 15.99 },
  { name: 'Шорти', category: 'Низ', price: 29.99 },
  { name: 'Куртка', category: 'Верхній одяг', price: 79.99 },
  { name: 'Плаття', category: 'Верхній одяг', price: 59.99 },
  { name: 'Капці', category: 'Взуття', price: 19.99 },
  { name: 'Спідниця', category: 'Верхній одяг', price: 39.99 },
  { name: 'Світер', category: 'Верхній одяг', price: 45.99 },
  { name: 'Костюм', category: 'Верхній одяг', price: 99.99 },
  { name: 'Кросівки', category: 'Взуття', price: 69.99 },
  { name: 'Рукавички', category: 'Аксесуари', price: 12.99 },
  { name: 'Пальто', category: 'Верхній одяг', price: 89.99 },
  { name: 'Топ', category: 'Верхній одяг', price: 19.99 },
  { name: 'Брюки', category: 'Низ', price: 55.99 },
  { name: 'Краватка', category: 'Аксесуари', price: 9.99 },
  { name: 'Блузка', category: 'Верхній одяг', price: 29.99 },
  { name: 'Капелюх', category: 'Головний убір', price: 18.99 },
  { name: 'Спортивний костюм', category: 'Верхній одяг', price: 74.99 },
  { name: 'Шнурівки', category: 'Аксесуари', price: 6.99 },
  { name: 'Кофта', category: 'Верхній одяг', price: 34.99 },
  { name: 'Ботильйони', category: 'Взуття', price: 59.99 },
  { name: 'Шарф', category: 'Аксесуари', price: 14.99 },
  { name: 'Шорти для бігу', category: 'Низ', price: 22.99 },
  { name: 'Футболка з довгим рукавом', category: 'Верхній одяг', price: 27.99 },
  { name: 'Джемпер', category: 'Верхній одяг', price: 38.99 },
  { name: 'Леггінси', category: 'Низ', price: 21.99 },
  { name: 'Пляжна сукня', category: 'Верхній одяг', price: 31.99 },
  { name: 'Кофеінка', category: 'Аксесуари', price: 8.99 },
]
